name: push to gcp
run-name: push to gcp
on: [push, workflow_dispatch]
env:
  REPO_DIR: /tmp/repo
  REPO_NAME: test-repo
permissions:
  contents: write
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: clone
        run: |
          rm -rf $REPO_DIR
          mkdir -p $REPO_DIR
          cd $REPO_DIR
          git clone https://github.com/thiago-a-souza/test-repo.git
      - name: push repo
        run: |
          cd $REPO_DIR/$REPO_NAME
          git push --mirror ssh://thi.alex@gmail.com@source.developers.google.com:2022/p/project-nl-330414/r/my-repo
