name: push to gcp
run-name: push to gcp
on: [push, workflow_dispatch]
permissions:
  contents: write
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: clone
        run: |
          rm -rf /tmp/repo
          mkdir -p /tmp/repo
          cd /tmp/repo
          git clone https://github.com/thiago-a-souza/test-repo.git
      - name: push repo
        run: |
          cd /tmp/repo/Docker
          git push --mirror ssh://thi.alex@gmail.com@source.developers.google.com:2022/p/project-nl-330414/r/my-repo
